Repository OpenLabsHQ/OpenLabs, pull requests merged in 2025-07, with the labels that each got.

#117 Add integration test to check connection from jumpbox to hosts
  api/src/app/enums/operating_systems.py
  api/tests/integration/api/v1/test_ranges.py
Labels: tests

#118 Remove Duplicate Step in First Range Tutorial
  docs/src/tutorials/deploy-your-first-range.md
Labels: documentation

#138 Enhance Project Roadmap
  docs/src/SUMMARY.md
  docs/src/index.md
  docs/src/roadmap.md
Labels: documentation

#139 Range Resource Parsing Error
  api/src/app/core/cdktf/ranges/base_range.py
  api/src/app/core/cdktf/stacks/aws_stack.py
  api/src/app/schemas/range_schemas.py
  api/src/app/schemas/subnet_schemas.py
  api/src/app/schemas/vpc_schemas.py
  api/src/app/utils/name_utils.py
  api/src/app/validators/names.py
  api/tests/api_test_utils.py
  api/tests/common/api/v1/config.py
  api/tests/conftest.py
  api/tests/integration/api/v1/test_blueprint_ranges.py
  api/tests/unit/api/v1/config.py
  api/tests/unit/api/v1/test_blueprint_hosts.py
  api/tests/unit/api/v1/test_blueprint_ranges.py
  api/tests/unit/api/v1/test_blueprint_subnets.py
  api/tests/unit/api/v1/test_blueprint_vpcs.py
  api/tests/unit/api/v1/test_ranges.py
  api/tests/unit/crud/test_crud_hosts.py
  api/tests/unit/crud/test_crud_ranges.py
  api/tests/unit/crud/test_crud_subnets.py
  api/tests/unit/crud/test_crud_vpcs.py
  api/tests/unit/validators/test_names.py
Labels: patch, backend

#140 chore(cli): fix url for cli after refactor
  cli/Makefile
  cli/README.md
  cli/cmd/auth/common.go
  cli/cmd/auth/login.go
  cli/cmd/auth/logout.go
  cli/cmd/auth/password.go
  cli/cmd/auth/register.go
  cli/cmd/auth/secrets.go
  cli/cmd/auth/status.go
  cli/cmd/auth/whoami.go
  cli/cmd/blueprints/common.go
  cli/cmd/blueprints/create.go
  cli/cmd/blueprints/delete.go
  cli/cmd/blueprints/export.go
  cli/cmd/blueprints/list.go
  cli/cmd/blueprints/show.go
  cli/cmd/blueprints/validate.go
  cli/cmd/config/set.go
  cli/cmd/config/show.go
  cli/cmd/ranges/deploy.go
  cli/cmd/ranges/destroy.go
  cli/cmd/ranges/jobs.go
  cli/cmd/ranges/list.go
  cli/cmd/ranges/shared.go
  cli/cmd/root.go
  cli/go.mod
  cli/internal/client/auth.go
  cli/internal/client/client.go
  cli/internal/progress/jobs.go
  cli/main.go
Labels: documentation
