Repository OpenLabsHQ/OpenLabs, pull requests merged in 2025-02, with the labels that each got.

#3 Project Boilerplate
  .autorc
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check_pr_labels.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  LICENSE
  NetworkParser.py
  README.md
  dev-requirements.txt
  enums/providers.py
  enums/specs.py
  pyproject.toml
  requirements.txt
  src/__init__.py
  src/app/__init__.py
  src/app/api/__init__.py
  src/app/api/v1/__init__.py
  src/app/api/v1/health.py
  src/app/api/v1/templates.py
  src/app/core/__init__.py
  src/app/core/cdktf/__init__.py
  src/app/core/logger.py
  src/app/enums/__init__.py
  src/app/enums/providers.py
  src/app/enums/specs.py
  src/app/main.py
  src/app/schemas/__init__.py
  src/app/schemas/openlabs.py
  src/app/schemas/templates.py
  src/app/validators/__init__.py
  src/app/validators/network.py
  tests/__init__.py
  tests/api/__init__.py
  tests/api/v1/__init__.py
  tests/api/v1/config.py
  tests/api/v1/test_health.py
  tests/api/v1/test_templates.py
  tests/core/__init__.py
  tests/validators/__init__.py
  tests/validators/test_network.py
Labels: minor

#4 Remove workflow permission from release.yml workflow
  .github/workflows/release.yml
Labels: patch

#5 Auto release GitHub App
  .github/workflows/release.yml
  README.md
Labels: patch

#6 Working Auto Release GH App Bypass
  .github/workflows/auto_release.yml
  .github/workflows/release.yml
  README.md
Labels: patch

#12 add codeowners file so we are auto requested for review
  .github/CODEOWNERS
Labels: enhancement, patch

#17 Add Docker configurations
  .docker/config.json
  Dockerfile
  README.md
  docker-compose.yml
  requirements.txt
  src/app/core/config.py
  src/app/core/db/database.py
  src/app/core/setup.py
  src/app/main.py
Labels: minor

#19 Clarify Docker Documentation
  README.md
Labels: documentation

#11 add some operating system AMIs and URNs
  src/app/enums/operating_systems.py
  src/app/schemas/openlabs.py
  tests/api/v1/test_templates.py
Labels: minor

#25 Update Mypy Precommit Dependencies
  .pre-commit-config.yaml
Labels: patch

#21 add .swp to gitignore to make my life easier
  .gitignore
Labels: patch

#23 Ignore enums directory when running black so we can have nice spacing
  pyproject.toml
  src/app/enums/operating_systems.py
  src/app/enums/specs.py
Labels: patch

#30 ignore .vscode folder to make my life easier
  .gitignore
Labels: documentation

#35 Specify minimum disk size for each OS
  src/app/enums/operating_systems.py
  src/app/validators/network.py
  tests/validators/test_network.py
Labels: minor

#46 SQLAlchemy ORM Models ✅
  Dockerfile
  dev-requirements.txt
  pyproject.toml
  src/app/api/v1/templates.py
  src/app/crud/crud_hosts.py
  src/app/crud/crud_ranges.py
  src/app/crud/crud_subnets.py
  src/app/crud/crud_vpcs.py
  src/app/main.py
  src/app/models/__init__.py
  src/app/models/openlabs_base_model.py
  src/app/models/openlabs_host_model.py
  src/app/models/openlabs_range_model.py
  src/app/models/openlabs_subnet_model.py
  src/app/models/openlabs_vpc_model.py
  src/app/schemas/openlabs_host_schema.py
  src/app/schemas/openlabs_range_schema.py
  src/app/schemas/openlabs_subnet_schema.py
  src/app/schemas/openlabs_vpc_schema.py
  src/app/schemas/templates.py
  src/app/utils/__init__.py
  src/app/validators/network.py
  tests/api/v1/test_health.py
  tests/api/v1/test_templates.py
  tests/conftest.py
  tests/validators/test_network.py
Labels: minor

#50 Cdktf
  Dockerfile
  dev-requirements.txt
  pyproject.toml
  requirements.txt
  src/app/api/v1/__init__.py
  src/app/api/v1/ranges.py
  src/app/api/v1/templates.py
  src/app/core/cdktf/.terraformrc
  src/app/core/cdktf/aws/.gitignore
  src/app/core/cdktf/aws/Pipfile
  src/app/core/cdktf/aws/Pipfile.lock
  src/app/core/cdktf/aws/aws.py
  src/app/core/cdktf/aws/aws_stack.py
  src/app/core/cdktf/aws/cdktf.json
  src/app/core/cdktf/providers.tf
  src/app/core/config.py
  src/app/enums/operating_systems.py
  src/app/enums/specs.py
  src/app/utils/cdktf_utils.py
  src/app/validators/id.py
  tests/api/v1/test_templates.py
  tests/conftest.py
  tests/core/cdktf/__init__.py
  tests/core/cdktf/aws/__init__.py
  tests/core/cdktf/aws/test_cdktf_aws.py
  tests/validators/test_id.py
Labels: minor

#52 Naming refactor
  src/app/api/v1/ranges.py
  src/app/api/v1/templates.py
  src/app/core/cdktf/aws/aws.py
  src/app/core/cdktf/aws/aws_stack.py
  src/app/crud/crud_host_templates.py
  src/app/crud/crud_hosts.py
  src/app/crud/crud_range_templates.py
  src/app/crud/crud_ranges.py
  src/app/crud/crud_subnet_templates.py
  src/app/crud/crud_subnets.py
  src/app/crud/crud_vpc_templates.py
  src/app/crud/crud_vpcs.py
  src/app/enums/operating_systems.py
  src/app/models/template_base_model.py
  src/app/models/template_host_model.py
  src/app/models/template_range_model.py
  src/app/models/template_subnet_model.py
  src/app/models/template_vpc_model.py
  src/app/schemas/template_host_schema.py
  src/app/schemas/template_range_schema.py
  src/app/schemas/template_subnet_schema.py
  src/app/schemas/template_vpc_schema.py
  tests/api/v1/test_templates.py
  tests/core/cdktf/aws/test_cdktf_aws.py
Labels: patch

#55 Add template delete endpoints
  src/app/api/v1/templates.py
  src/app/crud/crud_host_templates.py
  src/app/crud/crud_range_templates.py
  src/app/crud/crud_subnet_templates.py
  src/app/crud/crud_vpc_templates.py
  src/app/models/template_base_model.py
  src/app/models/template_host_model.py
  src/app/models/template_range_model.py
  src/app/models/template_subnet_model.py
  src/app/models/template_vpc_model.py
  tests/api/v1/test_templates.py
  tests/crud/__init__.py
  tests/crud/crud_mocks.py
  tests/crud/test_crud_host_templates.py
  tests/crud/test_crud_range_templates.py
  tests/crud/test_crud_subnet_templates.py
  tests/crud/test_crud_vpc_templates.py
  tests/validators/test_id.py
Labels: patch
