Repository OpenLabsHQ/OpenLabs, pull requests merged in 2025-03, with the labels that each got.

#63 Update .autorc
  .autorc
Labels: documentation

#56 Add ownership to templates and ranges + Implement auth endpoints
  CHANGELOG.md
  Dockerfile.dev
  README.md
  requirements.txt
  src/__init__.py
  src/app/__init__.py
  src/app/api/__init__.py
  src/app/api/v1/__init__.py
  src/app/api/v1/auth.py
  src/app/api/v1/ranges.py
  src/app/api/v1/templates.py
  src/app/api/v1/users.py
  src/app/core/__init__.py
  src/app/core/auth/__init__.py
  src/app/core/auth/auth.py
  src/app/core/cdktf/__init__.py
  src/app/core/config.py
  src/app/core/setup.py
  src/app/crud/crud_host_templates.py
  src/app/crud/crud_range_templates.py
  src/app/crud/crud_subnet_templates.py
  src/app/crud/crud_users.py
  src/app/crud/crud_vpc_templates.py
  src/app/enums/__init__.py
  src/app/models/__init__.py
  src/app/models/secret_model.py
  src/app/models/template_base_model.py
  src/app/models/user_model.py
  src/app/schemas/__init__.py
  src/app/schemas/message_schema.py
  src/app/schemas/secret_schema.py
  src/app/schemas/user_schema.py
  src/app/utils/__init__.py
  src/app/utils/crypto.py
  src/app/validators/__init__.py
  src/app/validators/network.py
  tests/__init__.py
  tests/api/__init__.py
  tests/api/v1/__init__.py
  tests/api/v1/config.py
  tests/api/v1/test_auth.py
  tests/api/v1/test_templates.py
  tests/api/v1/test_users.py
  tests/core/__init__.py
  tests/core/cdktf/__init__.py
  tests/core/cdktf/aws/__init__.py
  tests/validators/__init__.py
Labels: minor

#70 increase number of worker threads so we can get response while deploy…
  Dockerfile
  docker-compose.dev.yml
Labels: patch
